### PR TITLE
remove Nim 1.2 and Nim 1.4 support

### PR DESCRIPTION
**Pull request by tersec**

### CODE REVIEW

**Comment by arnetheduck** [comment]
we should wait a bit here - using std/tasks might not be a great idea after all, so we might want to recycle the shim and make it official instead - see https://github.com/nim-lang/Nim/pull/21859, ie std/tasks is basically an experimentation ground for upstream threading work

**Comment by tersec** [comment]
Well, this change is a no-op for 1.6 and newer. It uses `std/tasks` already, and has been doing so as long as anyone's been using `nim-taskpools` with Nim 1.6 .

**Comment by tersec** [comment]
But sure, that was just a nice cleanup, so https://github.com/status-im/nim-taskpools/pull/32/commits/b875b90ba7787d792df2ea226645efe375f4cecf undoes that part.

**Comment by arnetheduck** [comment]
alright - I was just about to agree with your point since we can remove the shims and copy the latest version from upstream instead (not sure if there are differences, but that's _actually_ what we should fork) so merging the original version SGTM

**Comment by tersec** [comment]
Alright, https://github.com/status-im/nim-taskpools/pull/32/commits/5726ff16b531897dc29ac5d66f2417eaef857235 restores that version

**Review by arnetheduck — APPROVED** [review]

**Pull request merged**
